### PR TITLE
removed bug of file handling

### PR DESCRIPTION
**Pull request by srbcheema1**
hei there was some bug regarding casting of string into dictionary
and also a minor fix regarding file handling
hope i havent messed up things :)

### CODE REVIEW

**Comment by Anishka0107** [comment]
Thanks for the PR @srbcheema1
Would you mind explaining the 2 bugs a bit more? It's been a long time since I saw all this :)

**Comment by srbcheema1** [comment]
first of all try to run your old version of code ..
try this 
............$ python3 file.py
pass
pass
...........$ python3 file.py
pass
2
gmail.com
gmail_pass
y
n
5
.............$ python3 file.py
pass
1
>>>>error here

........................................................................
then try the same of new version

**Comment by srbcheema1** [comment]
bug#1 was you were trying to f.read() into dictionary ... which was meaningless if there is single value in f.read() ...
coz 
>>>dict("{'key','value'}") 
it will give error

**Comment by Anishka0107** [comment]
Aha! Thanks for the fix

**Pull request merged**
